import { StyleSheet } from 'react-native';

// Shared light palette keeps status, text, and controls consistent across screens.
// Colors follow the Haposoft 10-year event site on a white background.
export const C = {
  bg: '#FFFFFF', surface: '#FFFFFF', surface2: '#F3FBF7', border: '#DCEFE5',
  text: '#06241C', muted: '#4B6159', accent: '#008557', accentSoft: '#E8F7EF',
  live: '#C93643', liveSoft: '#FFF0F1', ok: '#176A4C', okSoft: '#EAF7F1',
  warn: '#956000', warnSoft: '#FFF7E5', en: '#008557', ja: '#7046A5',
};

export const styles = StyleSheet.create({
  root: { flex: 1, backgroundColor: C.bg },
  flex: { flex: 1 },
  header: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between',
    paddingHorizontal: 20, paddingTop: 10, paddingBottom: 12, backgroundColor: C.bg },
  brandRow: { flexDirection: 'row', alignItems: 'center', flexShrink: 1 },
  logo: { width: 110, height: 20, resizeMode: 'contain' },
  brandDivider: { width: 1, height: 22, backgroundColor: C.border, marginHorizontal: 10 },
  brand: { color: C.text, fontSize: 19, fontWeight: '800' },
  pill: { minHeight: 34, maxWidth: '100%', flexDirection: 'row', alignItems: 'center',
    borderRadius: 20, paddingHorizontal: 10, marginLeft: 8 },
  dot: { width: 7, height: 7, borderRadius: 4, marginRight: 6 },
  pillText: { fontSize: 13, fontWeight: '700', flexShrink: 1 },

  welcomeContent: { paddingHorizontal: 20, paddingBottom: 32, width: '100%', maxWidth: 560, alignSelf: 'center' },
  intro: { paddingTop: 18, paddingBottom: 20 },
  title: { color: C.text, fontSize: 29, fontWeight: '800', lineHeight: 35, letterSpacing: -0.8 },
  description: { color: C.muted, fontSize: 15, lineHeight: 22, marginTop: 12 },
  notice: { padding: 14, borderRadius: 14, backgroundColor: C.accentSoft, marginBottom: 16 },
  noticeText: { color: C.text, fontSize: 14, lineHeight: 20 },
  noticeError: { backgroundColor: C.liveSoft, borderColor: '#F4C8CD', borderWidth: 1 },
  noticeErrorText: { color: '#9D2631' },
  retryButton: { minHeight: 48, alignItems: 'center', justifyContent: 'center',
    borderColor: C.accent, borderWidth: 1, borderRadius: 14, marginBottom: 16 },
  retryText: { color: C.accent, fontSize: 15, fontWeight: '700' },

  card: { backgroundColor: C.surface, borderColor: C.border, borderWidth: 1,
    borderRadius: 20, padding: 18, marginBottom: 14 },
  sectionTitle: { color: C.text, fontSize: 19, fontWeight: '800', letterSpacing: -0.3 },
  sectionHint: { color: C.muted, fontSize: 14, lineHeight: 20, marginTop: 5, marginBottom: 16 },
  fieldLabel: { color: C.text, fontSize: 13, fontWeight: '700', marginTop: 16, marginBottom: 8 },
  inputRow: { flexDirection: 'row', alignItems: 'center' },
  input: { flex: 1, minHeight: 50, backgroundColor: C.surface2, borderColor: C.border,
    borderWidth: 1, borderRadius: 12, paddingHorizontal: 14, paddingVertical: 10,
    color: C.text, fontSize: 15 },
  codeInput: { fontSize: 21, fontWeight: '800', letterSpacing: 5, textAlign: 'center' },
  smallAction: { minHeight: 50, minWidth: 62, marginLeft: 8, paddingHorizontal: 12,
    borderRadius: 12, backgroundColor: C.accent, justifyContent: 'center', alignItems: 'center' },
  smallActionText: { color: C.surface, fontSize: 14, fontWeight: '800' },
  outlineAction: { minHeight: 50, minWidth: 66, marginLeft: 8, borderColor: C.border,
    borderWidth: 1, borderRadius: 12, justifyContent: 'center', alignItems: 'center' },
  primaryBtnText: { color: C.surface, fontSize: 16, fontWeight: '800' },
  secondaryBtn: { minHeight: 52, marginTop: 16, borderRadius: 14,
    borderColor: C.accent, borderWidth: 1, backgroundColor: C.accentSoft,
    flexDirection: 'row', gap: 8, justifyContent: 'center', alignItems: 'center' },
  secondaryBtnText: { color: C.accent, fontSize: 15, fontWeight: '800' },
  pressed: { opacity: 0.62 },
  disclosure: { minHeight: 48, flexDirection: 'row', justifyContent: 'space-between',
    alignItems: 'center', marginTop: 10, borderTopWidth: 1, borderTopColor: C.border },
  disclosureText: { color: C.accent, fontSize: 14, fontWeight: '700' },
  settingsHeader: { minHeight: 52, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' },
  settingsLabel: { color: C.text, fontSize: 14, fontWeight: '700' },
  sessionContent: { flexGrow: 1, paddingBottom: 28, paddingHorizontal: 20, width: '100%', maxWidth: 600, alignSelf: 'center' },
  codeBanner: { minHeight: 74, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between',
    borderRadius: 18, backgroundColor: C.accentSoft, paddingHorizontal: 18, marginBottom: 10 },
  codeBannerLabel: { color: C.accent, fontSize: 10, fontWeight: '800', letterSpacing: 0.8 },
  codeBannerValue: { color: C.text, fontSize: 25, fontWeight: '800', letterSpacing: 3, marginTop: 2 },
  micPanel: { alignItems: 'center', backgroundColor: C.surface, borderColor: C.border,
    borderWidth: 1, borderRadius: 20, paddingTop: 16, paddingBottom: 18, marginBottom: 16 },
  micTitle: { color: C.text, fontSize: 19, fontWeight: '800', textAlign: 'center' },
  micSubtitle: { color: C.muted, fontSize: 13, lineHeight: 19, textAlign: 'center',
    paddingHorizontal: 20, marginTop: 4 },
  micWrap: { width: 190, height: 190, alignItems: 'center', justifyContent: 'center', marginTop: 6 },
  ring: { position: 'absolute', width: 128, height: 128, borderRadius: 64, backgroundColor: C.live },
  micButton: { width: 128, height: 128, borderRadius: 64, backgroundColor: C.accent,
    alignItems: 'center', justifyContent: 'center' },
  micButtonLive: { backgroundColor: C.live },
  interimCard: { backgroundColor: C.accentSoft, borderRadius: 14, padding: 14, marginBottom: 10 },
  interimTag: { color: C.accent, fontSize: 10, fontWeight: '800', letterSpacing: 0.7, marginBottom: 5 },
  interim: { color: C.text, fontSize: 15, lineHeight: 21 },
  captionList: { paddingHorizontal: 20, paddingBottom: 20, flexGrow: 1 },
  emptyCard: { flex: 1, minHeight: 130, justifyContent: 'center', alignItems: 'center',
    borderRadius: 16, borderStyle: 'dashed', borderColor: C.border, borderWidth: 1, padding: 18 },
  empty: { color: C.muted, fontSize: 13, lineHeight: 19, textAlign: 'center', marginTop: 5 },
  caption: { backgroundColor: C.surface, borderColor: C.border, borderWidth: 1,
    borderRadius: 16, padding: 15, marginBottom: 9 },
  captionVi: { color: C.text, fontSize: 16, fontWeight: '700', lineHeight: 23 },
  langRow: { flexDirection: 'row', alignItems: 'flex-start', marginTop: 10 },
  langTag: { width: 31, fontSize: 12, fontWeight: '800', marginTop: 2 },
  captionLang: { flex: 1, color: C.text, fontSize: 15, lineHeight: 21 },
  captionPending: { color: C.muted, fontSize: 13, marginTop: 10 },
  captionError: { color: C.live },

  scannerRoot: { flex: 1, backgroundColor: C.bg, alignItems: 'center', justifyContent: 'center' },
  scanFrame: { width: 230, height: 230, borderColor: C.surface, borderWidth: 3,
    borderRadius: 22, backgroundColor: 'transparent' },
  scanHint: { color: C.text, backgroundColor: C.surface, overflow: 'hidden',
    borderRadius: 10, paddingHorizontal: 14, paddingVertical: 10, marginTop: 22, fontSize: 14, fontWeight: '700' },
  scanClose: { position: 'absolute', bottom: 42, minHeight: 50, paddingHorizontal: 24,
    borderRadius: 14, backgroundColor: C.surface, flexDirection: 'row', gap: 8, alignItems: 'center' },
  scanCloseText: { color: C.accent, fontSize: 15, fontWeight: '800' },
  iconButton: { width: 48, height: 48, borderRadius: 14, alignItems: 'center', justifyContent: 'center' },
  iconLabel: { flexDirection: 'row', alignItems: 'center', gap: 10, flexShrink: 1 },
  scanButton: { minHeight: 108, borderRadius: 16, backgroundColor: C.accent, justifyContent: 'center', alignItems: 'center', gap: 10 },
  standaloneInput: { flex: 0, width: '100%' },
  createSection: { borderColor: C.border, borderWidth: 1, borderRadius: 18, backgroundColor: C.surface, paddingHorizontal: 18 },
  createBody: { paddingBottom: 18 },
  modalHeader: { minHeight: 68, paddingHorizontal: 20, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' },
  captionLink: { minHeight: 60, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', borderRadius: 16, paddingHorizontal: 18, backgroundColor: C.surface, borderWidth: 1, borderColor: C.border },
  captionCount: { color: C.muted, fontSize: 14 },

});
